// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAep-q2b65fyOUogQXawKFkevqCaqMomtY',
    appId: '1:927910360274:web:de5e41363157b61788a90b',
    messagingSenderId: '927910360274',
    projectId: 'projeto-flutter3',
    authDomain: 'projeto-flutter3.firebaseapp.com',
    storageBucket: 'projeto-flutter3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMNOYu99yC126RjlFdUgzildWH7pRcInc',
    appId: '1:927910360274:android:dd55701845a5f43e88a90b',
    messagingSenderId: '927910360274',
    projectId: 'projeto-flutter3',
    storageBucket: 'projeto-flutter3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK3uWnNoNfJDUMuTR5SK_Sr_UTsLrOG7g',
    appId: '1:927910360274:ios:4fc41ffcd59fad7d88a90b',
    messagingSenderId: '927910360274',
    projectId: 'projeto-flutter3',
    storageBucket: 'projeto-flutter3.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK3uWnNoNfJDUMuTR5SK_Sr_UTsLrOG7g',
    appId: '1:927910360274:ios:4fc41ffcd59fad7d88a90b',
    messagingSenderId: '927910360274',
    projectId: 'projeto-flutter3',
    storageBucket: 'projeto-flutter3.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAep-q2b65fyOUogQXawKFkevqCaqMomtY',
    appId: '1:927910360274:web:fb4e97f2a7fd65c788a90b',
    messagingSenderId: '927910360274',
    projectId: 'projeto-flutter3',
    authDomain: 'projeto-flutter3.firebaseapp.com',
    storageBucket: 'projeto-flutter3.appspot.com',
  );
}
